services:
  # Adatbázis konténer
  db:
    image: mongodb/mongodb-community-server:8.0-ubuntu2204
    container_name: inventory-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # Saját Backend Container
  backend:
    build:
      context: ./Backend/MyInventoryApi
      dockerfile: Dockerfile
    container_name: inventory-api
    ports:
      - "5001:8080"
    environment:
      - ConnectionStrings__MongoDb=mongodb://db:27017
    depends_on:
      - db

  #  Angular Frontend Container
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: inventory-frontend
    ports:
      - "4200:80"  # A localhost:4200-on fogod elérni, ami a belső Nginx 80-as portjára mutat
    depends_on:
      - backend

volumes:
  mongo-data: